(include_subdirs unqualified)

(executable
  (name Main)
  (modules (:standard))
  (libraries
    fstar.lib
    zarith_stubs_js)
  (modes byte exe js)

  (js_of_ocaml
    (flags (:standard --enable effects))
    (javascript_files thread_runtime.scheduler.js))
)

(env
  (_
    (flags (:standard -w -A))
    (js_of_ocaml
      (compilation_mode whole_program))))